### ISSUE TITLE
Fix Many Duplicate Reports

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#101]
A user can be reported many times by the same user. Cf:

<img width="1169" alt="Screenshot 2021-12-23 at 11 20 16" src="https://user-images.githubusercontent.com/191881/147226580-2b353b38-c8fc-481b-8ef3-375794a18588.png">

Here, it looks like those 2 users were just playing together for a year... A old lady might have clicked "Report" many times by mistake (?).

Anyway. The user above have 204 reports, so he appears on top of the "reported users" list. However, those 204 reports are only from 2 different users, so he really isn't the most reported user.

---

- in `ganomede-users`. Make sure `/reported-users` only count "distinct" reports (with different username). For example, the user above should have a `total` of `2`.
- in `ganomede-admin`. Think of a better way to show duplicate reports (above, we could show: `itir921 (190x)`, the date shown when "hover" could be "from 14/4/2019 to 13/12/2021")

**Comment by HusseinTaha** [comment]
ganomede-users /reported-users endpoint is adjusted, a PR is submitted [here](https://github.com/j3k0/ganomede-users/pull/65#issue-1089357633)
