### ISSUE TITLE
Virtualcurrency requests in https

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#12]
Any way I can switch to making https requests to virtualcurrency?

If not, that would be required.

**Comment by elmigranto** [comment]
Added `protocol` to config, probably needs env var to go along with it?

**Comment by j3k0** [comment]
Yes, an env var is required as well.

**Comment by elmigranto** [comment]
Added `VIRTUAL_CURRENCY_PORT_8080_TCP_PROTOCOL`.
