### ISSUE TITLE
Persistent sessions

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#13]
It seems like restarting the server looses the logged-in user session.

It probably also means that if 2 instances of the server run behind a load-balancer, it won't work well either.

in `auth.js`:
 * token.create(username) should return env var `ADMIN_TOKEN`.
 * token.consume(username) should compare with `ADMIN_TOKEN`.

(That's the most lazy implementation of it, that saves us from using a database...)

**Comment by elmigranto** [comment]
> It seems like restarting the server looses the logged-in user session.

Not quite — `/` shows login form, no matter of the logged in state at the moment. And if you relogin, it changes your `token` cookie, and it doesn't match admin's any longer.

I'll fix the form so it doesn't show up for users with valid `token`.

One issue I can see is that whoever logs in, stays logged in, even we change the password (perhaps generate `ADMIN_TOKEN` based on username+password).

**Comment by elmigranto** [comment]
Merge in `react-router` branch and did a login form in it. Made changes to `develop` so it isn't broken there. Commits:
  - https://github.com/j3k0/ganomede-admin/commit/7da45945ac313cd9b7b8e8f9c19372a09568d131
  - https://github.com/j3k0/ganomede-admin/commit/1f58679f4eb9edb9142f94d04624a94b047a97a2

**Comment by j3k0** [comment]
Still, the `token.create()` method generates a random token that is only stored in memory, so it will be lost when the app is restarted, and it will be valid only on a single instance. If we run multiple instances of the ganomede-admin server behind a load-balancer, it will fail (because only 1 instance will know the value for the authentication token).
