### ISSUE TITLE
Implement "Packs"

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#18]
Add a "Packs" section to edit the values of virtual currency packs.

See the virtualcurrency module Packs API here: https://github.com/j3k0/ganomede-virtualcurrency#retrieve-the-list-of-packs-get

 * It's __not__ necessary to add new packs
 * Only editing existing pack's `amount` field is required.
 * Only display: `id` (read only) `currency` (read only) and `amount` (editable).

Same presentation as the "Items" page.

**Comment by j3k0** [comment]
@elmigranto this is urgent. Do you have good availability this week? I'll handle the task if not.

**Comment by elmigranto** [comment]
Sure, I'll do it asap.

**Comment by elmigranto** [comment]
@j3k0 #22 is ready to merge.

Let me know if you want any other functionality other than editing amount.

**Comment by j3k0** [comment]
It's all good. thanks
