### ISSUE TITLE
Implement "Items"

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#3]
Implement the "Items" feature as a client of [ganomede-virtualcurrency](https://github.com/j3k0/ganomede-virtualcurrency) API.

CRUD for the store items defined by a ganomede-virtualcurrency instance. The design of the pages is good enough as it is in current status.

**Comment by elmigranto** [comment]
How do we link to other services? I see "Servers links" env vars, but not sure what those are.

I remember there being some sort of services registry, but for now I just did simplest possible thing: separate env var for each ganomede app (https://github.com/j3k0/ganomede-admin/tree/feature/vcurrency-items#other-microservices).

**Comment by j3k0** [comment]
Server Links are nothing really... Just a collection of links to display on the UI.

Yes, ENV var for each micro-service, as with other modules. In the spirit of coherence, I would use:

 - `VIRTUAL_CURRENCY_PORT_8080_TCP_ADDR`
 - `VIRTUAL_CURRENCY_PORT_8080_TCP_PORT`
 - `USERS_PORT_8080_TCP_ADDR`
 - `USERS_PORT_8080_TCP_PORT`
 - etc.

Those names look weird, but it's what Docker auto-generates when linking services together, so this turns out to be convenient.
