### ISSUE TITLE
Data: Batch import lists from CSV

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#33]
**New feature**: batch import lists (arrays) from CSV files.

Add a button on the "Data" page: _"Import Lists from CSV"_.

This will create (or update) a number of documents.

For each column in the CSV file:
 
 - first row is the document ID (if it's empty, ignore the column).
 - subsequent rows are the elements of the list (stop at the first empty cell).

**Example:**

CSV:
```csv
fr:animals,fr:towns
chien,paris
chat,rouen
elephant,toulouse
souris,
```

Generates:

![screen shot 2016-11-13 at 18 28 12](https://cloud.githubusercontent.com/assets/191881/20247216/35471350-a9cf-11e6-8d01-cddbacaa20c8.png)

**Comment by elmigranto** [comment]
If I'm getting this correctly, example CSV will generate 2 documents:

* ID `fr:animals` with values in first column of rows `2..N`;
* ID `fr:towns` with values in second column of rows `2..N`.

Those should be ordered as in CSV — generated JSON array would contain animal / town in the order they appear in CSV. So first animal is "chien", and first town is "paris", and so on…

**Comment by j3k0** [comment]
That's it

**Comment by elmigranto** [comment]
Okay, added initial version in #34, waiting for review.

One caveat may be that it does all the work in-memory inside the browser, so if CSV files will be huge we'll need to change that. On the other hand, we are buffering stuff pretty much everywhere server-side, so I assume it won't be a problem here. Let me know if that's not the case, though!
