### ISSUE TITLE
Data: can't preview/edit documents

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#38]
<img width="1205" alt="screen shot 2017-04-14 at 11 21 44" src="https://cloud.githubusercontent.com/assets/191881/25038009/07aa71aa-2105-11e7-897b-914ec0d89ff8.png">

I now get the above error when trying to read "data" document on the admin interface.

Server-side logs show nothing. Client side as well (except a react-deprecation warning:

<img width="715" alt="screen shot 2017-04-14 at 11 27 43" src="https://cloud.githubusercontent.com/assets/191881/25038078/6b78f1fc-2105-11e7-94e9-a92fb0493f83.png">

This is urgent! I need to be able to edit documents (that's why I discovered the issue)

**Comment by j3k0** [comment]
This `Z_DATA_ERROR` is zlib-related. Strange

**Comment by j3k0** [comment]
Safari is little more verbose:

<img width="769" alt="screen shot 2017-04-14 at 11 55 36" src="https://cloud.githubusercontent.com/assets/191881/25038846/6a25e748-2109-11e7-86e6-826ee24d577f.png">

**Comment by j3k0** [comment]
(bundle.js line 12184 is just Zlib's javascript class's `onerror` handler)

**Comment by elmigranto** [comment]
Looks like trying ungzip spmething that wasn't compressed.

**Comment by elmigranto** [comment]
These might be in server logs from data (or wherever we store docs), not admin.

**Comment by j3k0** [comment]
Indeed, seems like data is stored gzipped in `data`

```
redis-proxy.redis.prod.wordsearch.marathon.mesos:24031> GET "data/v1:NL:VERZORGING"
"\x1f\xc2\x8b\b\x00\x00\x00\x00\x00\x00\x03EP[\xc2\x8e\xc3\x83 \x0c\xc2\xbcK\xc2\xbe\xc3\xb7\x12Sp\b\xc3\xa5ad\xc2\xa0QS\xc3\xad\xc3\xbd\xc2\xaf\xc2\xb1\xc3\x98\xc2\xa9\xc2\xb4?x0\xc2\x9e\a\xc3\xbel\xc3\x823\xc3\x90\xc3\xb6\xc2\xb3\x15t\a\xc3\x81B\xc2\x8d\xc3\x89\xc2\x93,\xc3\xa0\xc2\x84\xc2\x8a>%\xc2\x94u>X\xc3\xba\xc2\xa0\xc2\xbcPw\a\xc2\xa0\x03\xc2\xaf\xc3\xb8\xc3\x94\xc3\xbbE\xc3\x94V\xc3\xa1\x1c\xc2\xbfB\xc3\x89\xc3\xa8-VGC\xc3\xa7\x0f\xc2\x94\xc3\x86\xc2\xac\x1a\xc3\x88\xc2\x9dT\xc2\xac7\xc3\x81[\xc2\xa9\xc3\x88\xc2\xbbq\x12M\xc3\x95(\xc3\x94\xc2\x9f*\x12\xc3\x8c\xc2\xa8A\xc3\xb6\xc2\xa9\xc3\xa3'\xc2\x86\xc2\xb5=Ow\xc2\x90\ty=\xc3\xb3\xc3\xac\xc3\x87\xc2\xaa\x03\xc2\xbb\xc3\x8d'\xc2\xb4f\xc3\x969.P5S\xc2\xb0r\xc2\xa2\xc3\x9e \xc3\x90\x14#\xc3\xb2\xc3\xba\xc2\x9a6\xc3\xba\xc2\x88\xc2\xbbfL'\xc3\xba0\a\xc2\xbe\x13\\,\xc3\x81\x02I\xc2\xba%bMf\xc3\xb2Z\x1b;u;\xc3\xb0\xc2\x84i\x7f\xc2\x89\x14\xc3\xbe\xc3\xbd\xc2\xab\x05\xc2\xaaJN2s\xc2\xb6\xc3\x86wa\x0f\xc3\xa1zY\xc3\x82\xc3\x82\xc3\x9eV\xc2\x9b\xc3\x89G\xc2\x9b\xc3\xad\x05H\x1a@8D\xc2\x8b2\xc2\x84\xc2\xaa\xc3\x9f~\xc3\xbf\x00o\xc3\x97\xc3\xa4B\xc2\xa3\x01\x00\x00"
redis-proxy.redis.prod.wordsearch.marathon.mesos:24031> GET "data/v1:NL"
"\x1f\xc2\x8b\b\x00\x00\x00\x00\x00\x00\x03MS\xc3\x8b\xc2\xae\xc3\x940\x0c\xc3\xbd\xc2\x95j\x16\xc2\xb0\xc2\x81\x1f\xc2\xb8;O\xc3\xa3i}\xc2\x93&\xc2\x91\xc2\x93\xc2\xb4R\xc3\x91] t\xc2\x85X!\x01;\xc3\x84\xc2\xbf\xc3\xa3\xc2\x99\xc3\x86\xc2\x9e\xc3\xae\xc3\x8e\xc2\xa9\x1f\xc3\xb1\xc2\xb1O\xc3\xbf^\xc2\xbe}\xc3\xbd\xc3\xb3\xc3\xbe\xc3\xbd\xc3\xa7\xc2\xaf\x1f\xc3\xaf\xc2\xbf//_.1\xc2\xbc\xc3\x808b)\xc2\x89\x18\xc3\x8b\xc3\xa5\xc3\x93\xc3\xa3C\xc2\xab\xc3\xa9\xc2\xa3\xc3\xa25\xc3\x85\xc3\x9a\x1a\x1f\xc3\xac\xc2\x8a\xc2\x9c0c\xc3\xac,$\\\xc2\x8c$d\xc2\x87L\xc2\xafJO\xc2\x91\xc3\x9e\xc3\xab\xc3\x8a\x10\xc3\x9d\xc2\x86\xc3\x98\xc2\x9b\xc2\x8d\xc2\x8cP\to\as\xc2\x84\xc2\xac\x15\xc2\x8e)z%\x18\xc3\x90WN\xc2\x91F8>\xc3\x9c`\xc2\xa1@\xc3\x98\tb\xc2\xa9\x1d\x12\xc3\x96R\xc3\x938+\xc3\xa7F\x1dN\xc3\x800\xc3\xb5\xc2\x8a\t\xc2\x83\xc3\xabH\xc3\x84\xc3\x84\xc2\x8a\xc3\x83\xc2\x87\xc3\xa1\xc2\x94:\xc2\xb7\xc2\x90e\xc2\x96X\xc2\xaa\x0e@\xc2\x92\xc3\x83\xc2\x84\xc2\xba\x03\x0f9\xc2\xab\x04\xc2\x8f\xc2\xac\xc2\xaf{\xc2\x8a\xc3\xae\xc2\xa9\xc3\xa0`\x1e\x16\xc3\x8b\x0c\xc3\xa8(N\xc2\x9d$S\xc3\xa7EX\xc2\x9c\xc3\x8a\xc3\x9c\xc2\xa8/)\xc3\x88\xc2\x8e4x\xc3\x87e\xc2\x9c!\x1fti;\xc2\xa1?p\x0c\xc2\x83Lh\xc2\x99i\x19f\xc2\xac\xc3\x83\xc2\xb3MjNtE\x19{;>db0I9\x05\xc2\xaa\xc2\xba\xc3\x82\xc3\x8cX3po,.\xc2\xa8\xc3\x90\xc3\xa4R]\x17\xc3\x93z\xc2\xba\x0c\xc2\xa7E\"6E\x19\xc3\xa9\xc3\xb3\xc2\x8d:F\xc3\x9ae\xc2\x9f\xc2\x9aY2b\xc2\xa8\xc2\x8d\xc2\x8c&\xc2\xae'hiM\xc2\x96\xc2\xb9\xc3\x88\xc3\xab=X!hH\xc2\x8e\xc3\x9e6#\xc3\x96i\x05\xc3\xbf\x18A\xc2\x99\xc3\x8d\xc2\xb6\"\xc2\xbf\x02\xc2\xb0\xc2\x83\xc3\x89\xc3\xb8\xc2\x9at\xc3\xbfB\xc3\xb6\xc3\x84\xc2\x93\xc2\x9d`\xc2\xa5R\xc2\xac0\xc2\xa0Z\x7f\x15cM\xc2\xab9\xc3\xa4^//O\xc2\x96\xc2\x99\xc2\xb0^!(\x11+\xc3\xb5\xc2\xba\xc2\xa7\xc2\xab7\xc3\x99\x1frT\"BO\x17\xc3\x9c\xc3\xae\xc2\xbe6\xc2\x81\xc3\x9b\xc3\x83Y\a\xc3\x9e\xc2\x93Ye\xc3\x9fp\xc2\xb9\xc3\xbf<o\xc3\xbf\xc3\xbe\x03\xc2\x8d<\x1ee\xc2\xad\x03\x00\x00"
```

**Comment by j3k0** [comment]
But no interesting logs in `data`

**Comment by elmigranto** [comment]
I'll take a look as soon as I get to computer.

**Comment by elmigranto** [comment]
Is it logged as upstream error in admin? Because when it is, admin replies to web ui with 500 and JSON of error, and it certainly looks like that's the case. Can't  remember whether fetch or request errors serialized this way (client error in web ui).

**Comment by j3k0** [comment]
Hitting data manually: https://XXX/data/v1/docs/NL

We get a valid JSON document, Response Headers:
 * **content-encoding:gzip**
 * content-length:419
 * content-type:application/json; charset=UTF-8
 * date:Fri, 14 Apr 2017 10:28:43 GMT
 * status:200

Hitting the [admin->data proxy](https://github.com/j3k0/ganomede-admin/blob/develop/server/data.router.js) manually: https://XXX/admin/v1/api/data/docs/NL

We're getting the JSON document as well, with similar headers.

Seems like the issue is client side.

**Comment by j3k0** [comment]
More info... When running the admin interface locally, there's no issue (which allows me to edit documents, making this less urgent). Transfer between server and browser aren't gzipped.

In prod, cloudflare and a bunch of proxy are between the browser and the admin server, one of those might think it's a good idea to gzip content (and add the relevant headers)... but the client seems not to like that.

**Comment by elmigranto** [comment]
So the admin module actually expects unpacked data (since it never sets `gzip` option to `true` on `request()` call), but I guess proxy does, so somehow things get mangled. I can't quite dig deeper myself for the time being, sorry, but try this:

```
diff --git a/server/utils.js b/server/utils.js
index 81ba456..3b39779 100644
--- a/server/utils.js
+++ b/server/utils.js
@@ -47,6 +47,7 @@ class Upstream {
       : this.prefix;
 
     options.json = true;
+    options.gzip = true;
 
     request(options, (err, res, body) => {
       // Check network errors.
```

**Comment by j3k0** [comment]
[4/20/17, 14:46:22] I got over the gzip error by bypassing Cloudflare. Base setup to enable the bug, have the requests go through the Cloudflare CDN. Setup is as such: Client -(https)-> Cloudflare -(https)-> Haproxy -(http)-> NodeJS apps. Seems like haproxy has nothing to do with this. Disabling Cloudflare fixes the issue.

**Comment by j3k0** [comment]
Replying to Skype question:

Yes, issue is the interaction with Cloudflare. However everything else is working fine, we need our requests to go through Cloudflare, because they provide the SSL certificate &rArr; we do want the client to see "invalid SSL certificate" errors on their browser.

**Comment by elmigranto** [comment]
There is some wierd stuff going on with content-encoding header (sometimes I saw it missing) and request (ungzipping even though no "content-encoding" received). Anyways, can you try doing this:

``` diff
diff --git a/web/js/utils.js b/web/js/utils.js
index d4aa4b2..3e52896 100644
--- a/web/js/utils.js
+++ b/web/js/utils.js
@@ -25,6 +25,7 @@ var utils = {
   xhr: function (options, callback) {
     options.url = url.resolve(String(window.location.origin), options.url);
     options.json = true;
+    options.gzip = false;
     request(options, callback);
   },
```

And I'll look more into request code and data's compression stuff.

**Comment by elmigranto** [comment]
I've noticed that regardless of `gzip` setting, browsers add their own Accept-Encoding stuff, maybe we do decompression twice if `gzip` is `true`, and browser does it for us if `gzip` is false.
