### ISSUE TITLE
Play well with renamed users

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#40]
When searching for a user, the admin module should first check if there's a user with the given "alias" tag, so it displays the right user.

In short: play well with user that changed their name.

**Comment by elmigranto** [comment]
Not sure what you mean. IIRC, it looks up `userId` and only allows stict matches (e.g. "jeko" won't find "jeko99"). My understanding is that we want to do multiple lookups, one for `userID` and one for `alias:tag` via directory (and tagizer if needed)? If so, how is this going to work around rename, or is tag immutable? Isn't userId also can not be changed and it is `alias:name` that user can edit?

**Comment by j3k0** [comment]
Yes, you need to look up the "tagized" version of what has been searched for as a tag alias in the directory. If you recall, aliases (thus tags) can change, but the previous value remains attached and reserved to the user. So, a link `tag` &rArr; `userid` will be immutable, searching by tag for "jeko" or "jeko99" will both always return the same user in the directory, even if decide to rename myself again.

I'm not sure if I'm clear.
