### ISSUE TITLE
Reset the user password

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#43]
Add a password reset button to the user page.

The button opens a sweetalert prompt for the new password, prefilled with a random sequence of characters. Use of https://github.com/bermi/password-generator would be nice.

Click "Reset" will make the request.

If successful, a confirmation dialog then shows: "The password for user USERNAME has been changed to NEWPASSWORD".

Ref: https://github.com/j3k0/ganomede-directory/blob/master/SERVER.md#edit-a-user-post

**Comment by elmigranto** [comment]
Docs for  password-generator mention its use of [`crypto.getRandomValues()`](http://caniuse.com/#feat=getrandomvalues), and I've been meaning to ask this for a while, which browsers are we targeting? I think `admin` was Chrome-only for a while, I've occasionally opened it in Safari and that's it; in fact, I don't even know if it compiles arrow functions and stuff to ES5 :)

**Comment by elmigranto** [comment]
> which browsers are we targeting? I think `admin` was Chrome-only

Switched to babelify with `es2017 react` presets, should not be a problem anymore.

**Comment by j3k0** [comment]
Great. It's not really defined which browser we are supposed to support on the admin interface, but I guess ES6 is still a little too bleeding edge to be a requirement. So babel is still welcome.

Will test all of that in the week.

ganomede-users's issue 36 (password reset error code) is now the most urgent (players still see a nice popup with "DocumentNotFound" instead of a proper error message)...

**Comment by elmigranto** [comment]
After a brief look at caniuse.com, it seems that anything that not Internet Explorer should work just fine: Firefox, whole WebKit family and Firefox all support stuff up to `async` / `await` at least for 2 version behind… But we leave it as is for now.

> users 36

Okay, will be looking into that next.
