### ISSUE TITLE
Display user using the `name` alias

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#46]
When the username needs to be displayed, if a name alias exists on the user, we should use it instead of displaying the id (because that's how the user knows himself).

Note (FYI) that tagizer(alias:name) === alias:tag ↠ generally users' will be searched by name (but the tag is case and potential mistake safe, it prevents confusions like letters I or l among others)..

**Comment by elmigranto** [comment]
> `tagizer(alias:name) === alias:tag`

Isn't `tag` derived from user ID? Or is it initially on registration and then updated if user sets `alias:name`?

**Comment by elmigranto** [comment]
Actually, it seems there is no way to change the name in the app, only location meta.

**Comment by elmigranto** [comment]
A bit off topic and we have this in place already, but…

> the tag is case and potential mistake safe

Agree about letter case, but with typos one as likely to mistype <kbd>b</kbd> instead of <kbd>n</kbd> as misread `I` as `l`.

**Comment by j3k0** [comment]
Sorry I didn't answer earlier.

 * When user registers: `alias:name` = `alias:id`
 * `alias:name` can change
 * Always true: `alias:tag = tagizer(alias:name)`

**Comment by j3k0** [comment]
> mistakes one as likely to mistype B instead of N as misread I instead of l or 1.

Tags only fix problems with fonts that make it hard to distinguish between some symbols, not user typos. We had a lot of issues with player claiming they can't invite their friend **JEKO**, just because their friend was actually called **JEK0** (monospace `JEK0 vs JEKO`) ... same with **eIMIGRANT0** and **elMlGRANTO** (monospace `eIMIGRANT0 vs elMlGRANTO`) --- I guess those 2 users were looking for trouble, but there were many like those.
