### ISSUE TITLE
Implement "Reward"

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#7]
Add a way to manually reward a user some currency.

Shell script as an example:

https://github.com/j3k0/ganomede-virtualcurrency/blob/master/tools/reward.sh

Maybe a good way would be to re-introduce the page with user details...

- [x] cleanup page that shows a search box allowing to enter the username
- [x] cleanup page that shows users' details:
  - [x] username
  - [x] coins balance (using ganomede-virtualcurrency)
  - [x] purchases (using ganomede-virtualcurrency)
  - [x] avatar image (using ganomede-avatar)
  - [x] location (using ganomede-users / metadata=location)
- [x] add a input box for amount and currency type

**Comment by elmigranto** [comment]
Is there a repo or specs for `users` service?

**Comment by j3k0** [comment]
Yes,

I guess what interest you is this: `GET /users/v1/:username/metadata/:key`

Like for instance this for a location: https://prod.ggs.ovh/users/v1/jeko/metadata/location

BTW for testing, when there are links to external services, I recently found out about [nock](https://github.com/node-nock/nock), that intercepts node's http(s) calls and adds some expectations. Pretty cool.

**Comment by elmigranto** [comment]
> search box allowing to enter the username

Would that require a full match (`elmig` -> user not found; `elmigranto` -> show a page) or is there any API for searching by username?

**Comment by j3k0** [comment]
There no api, full match only.

**Comment by elmigranto** [comment]
> coins balance (using ganomede-virtualcurrency)

j3k0/ganomede-virtualcurrency#22
j3k0/ganomede-virtualcurrency#23

**Comment by elmigranto** [comment]
Is there a way to check whether user exists? `users/metadata` gives okay response for any input, `avatars` might not exist (but user itself does), and `virtualcurrency` defaults to no transactions and 0 balance for non-existent entries.

**Comment by j3k0** [comment]
This doesn't matter. Just threat non existing users as if they existed.

**Comment by elmigranto** [comment]
Merged #25 myself (into `develop`), since there were some git conflicts. Here are [the changes](https://github.com/j3k0/ganomede-admin/pull/25/files) and how it looks:
![2016-04-30 14 52 59](https://cloud.githubusercontent.com/assets/886388/14935697/5e75f7e6-0ee3-11e6-9403-584754828f04.png)

**Comment by elmigranto** [comment]
**Don't merge into `master` just yet!**

There is a bug where Login Form won't be shown to users. Fixing it right now in #26.

**Comment by elmigranto** [comment]
Fixed that.
