### ISSUE TITLE
Moderate chat

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#84]
New page to display the content of a chat room

2 inputs: "user1, user2"

below:
- show the chat between those players.

To get the chat, it's `ganomede-chat`: https://github.com/j3k0/ganomede-chat#room-chatv1authauthtokenroomsroomid

Room id is `<game_id>/<user1>/<user2>`. IMPORTANT user1 and user2 sorted alphabetically.

If `from` is `$$`, show the message in gray.

Don't forget to `encodeURIComponent` the ROOM_ID

Example: `<game_id>` can be `triominos/v1`, need to be configurable with env var.

Connection with ganomede-chat configured with env var.

**Comment by HusseinTaha** [comment]
Task accomplished:

Final-result
<img width="1394" alt="Screen Shot 2021-11-08 at 10 52 43 PM" src="https://user-images.githubusercontent.com/11071646/140990130-31dde54e-fb10-4457-8c76-26ffe0d3c7bb.png">

Tests added also for the new api, can you please review as well.
