### ISSUE TITLE
Improve display of the transaction history

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#87]
- [x] The transaction list is not correctly sorted by date.
- [x] We would like to display it as an Array with the following columns: `Date, Item, Amount, Balance`
- [x] We would like a separate list for each currency (with a header showing the currency)

Final result:
---

#### gold-coin

| Date | Item | Amount | Balance |
|---|---|---|---|
| 2021-01-01 | single player | 1 | 1 |
| 2021-01-04 | single player | 1 | 2 |
| 2021-01-05 | multi player | 2 | 4 |
| 2021-01-05 | purchase strawberry | -1 | 3 |

#### silver-coin

| Date | Item | Amount | Balance |
|---|---|---|---|
| 2021-01-03 | large pack | 100 | 100 |
| 2021-01-03 | hint | -10 | 90 |
| 2021-01-09 | hint | -10 | 80 |

**Comment by j3k0** [comment]
@HusseinTaha This task wasn't well specified sorry.

The idea here is not just to fix the scrolling, but a deeper change. I'll update the description right away.

**Comment by HusseinTaha** [comment]
The task is accomplished, please check the below screenshot.

<img width="1280" alt="Screen Shot 2021-11-06 at 6 08 50 AM" src="https://user-images.githubusercontent.com/11071646/140596028-b18680cd-31a2-4499-983e-38fa7d62b6cf.png">

However i didn't push yet. How to calculate the balance column? cause I can't see that prop inside the json returned.
Can you please advise?

**Comment by j3k0** [comment]
Good!

The balance is like in a bank account: accumulate the amount of each transaction over time. In the silver example above, you would have 10, then 12, then 13, then 14.

Another thing, you could remove the "Actions" column and just make the "item" clickable.

**Comment by HusseinTaha** [comment]
I updated the changes, but I am not sure why the commits are not showing here .. 
anwyays here is a link => #94
